SELECT CUSTFIRSTNAME||','||CUSTLASTNAME AS "CUSTNAME", CUSTCITY AS "CITY", CUSTSTATE AS "STATE" FROM CUSTOMERS 
ORDER BY CUSTSTATE DESC,CUSTCITY;



SELECT CUSTFIRSTNAME||','||CUSTLASTNAME AS "CUSTNAME", CUSTCITY
AS "CITY", CUSTSTATE AS "STATE" FROM CUSTOMERS ORDER BY 3 desc,2;


SELECT ORDERNUMBER, PRODUCTNUMBER,QUOTEDPRICE, QUANTITYORDERED, QUOTEDPRICE*QUANTITYORDERED 
AS "Extened Price", QUOTEDPRICE*QUANTITYORDERED*1.13 
AS "Line Total" 
FROM ORDER_DETAILS;

SELECT ORDERNUMBER, PRODUCTNUMBER,QUOTEDPRICE, QUANTITYORDERED, QUOTEDPRICE*QUANTITYORDERED 
AS "Extened  Price", QUOTEDPRICE*QUANTITYORDERED*1.13 AS "Line Total" 
FROM ORDER_DETAILS 
ORDER BY "Line Total" DESC;


SELECT CustomerID, CustFirstName||','||CustLastName AS "Customer Name", CustStreetAddress,
CustCity, CustState
FROM CUSTOMERS
WHERE CUSTFIRSTNAME LIKE '_a%' AND CUSTSTREETADDRESS LIKE '%Lane';


SELECT*FROM PRODUCTS
WHERE PRODUCTNUMBER < QUANTITYONHAND  AND( PRODUCTNAME LIKE '%Bike' OR PRODUCTNAME LIKE '%Tires')
ORDER BY RETAILPRICE DESC;


SELECT*FROM VENDORS
WHERE VENDSTATE IN('CA','NY','WA')AND VENDPHONENUMBER NOT LIKE '(425)%'
ORDER BY VENDSTATE, VENDCITY ;

/*List all orders created in the last week of September 2007, 
that were sold by employee 704 or employee 708 and sort it by EmployeeID*/ 

ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD';
SELECT*FROM ORDERS
WHERE  EMPLOYEEID IN('704','708') AND (OrderDate Between '2007-09-24' AND '2007-09-30')
ORDER BY EMPLOYEEID ASC;


/*List the Customer Name (first and last), and Ship Date for Order 806: */


SELECT CustFirstName, CustLastName, ShipDate
FROM CUSTOMERS INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
AND ORDERNUMBER=806;

/*List all product names and the vendor’s name 
who sells the product:, sort by the vendor name */


SELECT PRODUCTNAME, VENDNAME
FROM PRODUCTS P INNER JOIN PRODUCT_VENDORS PV 
ON P.PRODUCTNUMBER = PV.PRODUCTNUMBER
INNER JOIN VENDORS V ON PV.VENDORID = V.VENDORID
ORDER BY VENDNAME, PRODUCTNAME;

/*List the customer’s name, product name and discount amount for all items on order 685 
that have been discounted (where quoted price is less than retail price) */


SELECT CUSTFIRSTNAME, CUSTLASTNAME, PRODUCTNAME, (RETAILPRICE - QUOTEDPRICE) AS "DISCOUNTED AMT."
FROM CUSTOMERS C INNER JOIN ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN ORDER_DETAILS OD ON O.ORDERNUMBER = OD.ORDERNUMBER
INNER JOIN PRODUCTS P ON OD.PRODUCTNUMBER = P.PRODUCTNUMBER
WHERE QUOTEDPRICE < RETAILPRICE AND OD.ORDERNUMBER= 685;

/*List the product numbers for products that we have purchased from more than one vendor (Hint use a Self Join to solve, 
see above for reference,
don’t forget to remove any duplicates) */


SELECT DISTINCT P1.PRODUCTNUMBER
FROM PRODUCT_VENDORS P1 INNER JOIN PRODUCT_VENDORS P2 
ON P1.PRODUCTNUMBER = P2.PRODUCTNUMBER
WHERE P1.VENDORID <> P2.VENDORID
ORDER BY P1.PRODUCTNUMBER;



/*Create Table categories */

  (CATEGORYID       NUMBER (8, 0) NOT NULL,
   CATEGORYNAME   VARCHAR2 (15) NOT NULL,
   DESCRIPTION      VARCHAR2 (300),
   CONSTRAINT CATEGORIES_CATEGORYID_pk PRIMARY KEY (CATEGORYID)
   );



